site_name: David Finster
site_description: About David Finster
site_author: David Finster
copyright: '&copy; <a href="https://www.dfinr.com">David Finster</a> - <a href="https://github.com/dfinr/dfinr.github.io/blob/mkdocs/LICENSE.md">CC BY-NC-ND 4.0</a>'
nav:
    - 'About': 'index.md'
    - 'Guitar': 
      - 'Shower Mat Pedalboard': 'guitar/pedalboard.md'
    - 'Blog': 
      - 'Backup': 'blog/Backup.md'
docs_dir: docs
remote_branch: site
use_directory_urls: true
dev_addr: 127.0.0.1:8000
theme:
  name: material
  palette:
    scheme: preference
  favicon: images/808080-512x512.png
  icon:
    logo: material/comment-account-outline
  plugins:
    - search
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - toc:
      permalink: true
      toc_depth: 3
    - toc.integrate
    - search.suggest
    - search.highlight
    - header.autohide
extra:
  social:
    - icon: fontawesome/brands/reddit
      link: https://www.reddit.com/user/dfinr  
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/dfinr
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/dfinr/  
    - icon: fontawesome/brands/stack-overflow
      link: https://stackoverflow.com/users/13642710/dfinr?tab=profile
    - icon: fontawesome/brands/twitch
      link: https://www.twitch.tv/dfinr
    - icon: fontawesome/brands/github
      link: https://github.com/dfinr
extra_css:
  - stylesheets/extra.css
